language: python
python:
#  - "2.5"
  - "2.6"
  - "2.7"
install:
  - pip install .
  - pip install -r requirements/default.txt Django==$DJANGO
before_script:
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=dbtemplates.test_settings
script:
  - django-admin.py jenkins
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
branches:
  only:
    - develop
